allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@tailwindcss/oxide': set this to true or false
  babylonjs: true
  prisma: true
onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
